#!/usr/bin/env python3

import argparse
import sys

import uchroma


def get_splotch():
    if args.splotch is None:
        return None
    return uchroma.color.Splotch[args.splotch.upper()]


parser = argparse.ArgumentParser()

parser.add_argument('device', type=str,
                    help='HID device to use (/dev/hidrawX)') 

action = parser.add_mutually_exclusive_group(required=True)
action.add_argument("-b", "--breathe", action='store_true')
action.add_argument("-d", "--disable", action='store_true')
action.add_argument("-l", "--starlight", action='store_true')
action.add_argument("-r", "--reactive", action='store_true')
action.add_argument("-s", "--spectrum", action='store_true')
action.add_argument("-t", "--static", action='store_true')
action.add_argument("-w", "--wave", action='store_true')

parser.add_argument('-x', '--splotch', type=str, help='Color splotch [earth|air|fire|water|sun|moon]')

args = parser.parse_args()

driver = uchroma.Driver(args.device)

try:
    if args.breathe:
        if not driver.breathe_effect(splotch=get_splotch()):
            sys.exit(1)

    elif args.disable:
        if not driver.disable_effects():
            sys.exit(1)

    elif args.starlight:
        if not driver.starlight_effect(splotch=get_splotch()):
            sys.exit(1)

    elif args.reactive:
        if not driver.reactive_effect():
            sys.exit(1)

    elif args.spectrum:
        if not driver.spectrum_effect():
            sys.exit(1)

    elif args.static:
        if not driver.set_color():
            sys.exit(1)

    elif args.wave:
        if not driver.wave_effect():
            sys.exit(1)

finally:
    driver.close()

print("OK")
