#!/usr/bin/env python3

import argparse
import asyncio
import functools
import logging
import signal
import sys

import gbulb

from uchroma.dbus import DeviceManagerAPI
from uchroma.device_base import BaseUChromaDevice
from uchroma.device_manager import UChromaDeviceManager


logging.basicConfig(stream=sys.stdout, level=logging.INFO)


TRACE = 5

class UChromaServer(object):

    def __init__(self):
        self._dbus = None

        gbulb.install()

        parser = argparse.ArgumentParser(description='UChroma daemon')
        parser.add_argument("-v", "--version", action='version', version='self.version')
        parser.add_argument("-d", "--debug", action='append_const', const=True,
                            help='Enable debug output')

        args = parser.parse_args()

        self._logger = logging.getLogger('uchroma.server')

        if args.debug is not None:
            if len(args.debug) > 0:
                level = logging.DEBUG
                if len(args.debug) > 1:
                    level = TRACE
                    self._logger.debug("TRACE logging enabled!")
                logging.getLogger().setLevel(level)
                asyncio.get_event_loop().set_debug(True)



    @asyncio.coroutine
    def _dm_callback(self, action: str, device: BaseUChromaDevice):
        self._logger.info('%s: %s', action, device)
        device.restore_prefs()


    def _shutdown_callback(self, loop):
        self._logger.info("Shutting down")
        loop.stop()


    def run(self):
        dm = UChromaDeviceManager()
        dm.callbacks.append(self._dm_callback)

        self._dbus = DeviceManagerAPI(dm)

        loop = asyncio.get_event_loop()

        for sig in (signal.SIGINT, signal.SIGTERM):
            loop.add_signal_handler(sig, functools.partial(self._shutdown_callback, loop))

        try:
            dm.monitor_start()
            self._dbus.run()

            loop.run_forever()

        except KeyboardInterrupt:
            pass

        finally:
            dm.monitor_stop()
            dm.close_devices()

            done, pending = loop.run_until_complete(asyncio.gather(*list(asyncio.Task.all_tasks())))
            print('pending tasks: %s' % pending)

            for task in done:
                done.result()

            loop.close()


if __name__ == '__main__':
    UChromaServer().run()

