name: uchroma
version: "1.9.90"
summary: Razer Chroma peripheral manager
description: |
  An advanced driver for the Razer Chroma line of peripherals.
  Supports lighting effects, custom animations, and more.

base: core22
grade: stable
confinement: strict

plugs:
  dbus:
    bus: session
    interface: dbus
    name: io.uchroma

slots:
  session-dbus-interface:
    bus: session
    interface: dbus
    name: io.uchroma

apps:
  uchroma:
    command: bin/gi-wrap uchroma

  uchromad:
    command: bin/gi-wrap uchromad
    daemon: simple
    plugs:
      - hardware-observe
      - hidraw
      - home
      - raw-usb
      - unity7

parts:
  uchroma:
    source: .
    plugin: python
    python-version: python3
    build-packages:
      - cython3
      - libhidapi-dev
      - python3-dev
      - python3-numpy
    stage-packages:
      - python3-gi

  gi-wrap:
    source: snap/
    plugin: dump
    organize:
      gi-wrap: bin/gi-wrap
