name: uchroma
version: "1.9.90"
summary: Razer Chroma peripheral manager
description: |
  An advanced driver for the Razer Chroma line of peripherals.
  Supports lighting effects, custom animations, and more.
license: LGPL-3.0-only
base: core22
grade: stable
confinement: strict

plugs:
  dbus:
    bus: session
    interface: dbus
    name: io.uchroma

slots:
  session-dbus-interface:
    bus: session
    interface: dbus
    name: io.uchroma

apps:
  uchroma:
    command: bin/uchroma
    plugs:
      - home

  uchroma-gtk:
    command: bin/uchroma-gtk
    extensions: [gnome]
    plugs:
      - home
      - unity7

  uchromad:
    command: bin/uchromad
    daemon: simple
    plugs:
      - hardware-observe
      - hidraw
      - home
      - raw-usb

parts:
  uchroma:
    source: .
    plugin: nil
    build-packages:
      - cargo
      - rustc
      - libhidapi-dev
      - libudev-dev
      - python3-dev
      - python3-pip
      - python3-venv
    stage-packages:
      - libhidapi-hidraw0
      - python3-gi
      - python3-gi-cairo
      - gir1.2-gtk-4.0
      - gir1.2-adw-1
    override-build: |
      pip3 install maturin installer
      make build MATURIN=maturin
      python3 -m installer --destdir=$SNAPCRAFT_PART_INSTALL dist/*.whl
      make install DESTDIR=$SNAPCRAFT_PART_INSTALL
